// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD32nIxqw91IZ8XOs8mS3yEu0rsKxVy3uY',
    appId: '1:201628199416:web:b96745e1078925fe068e0d',
    messagingSenderId: '201628199416',
    projectId: 'my-task-c7a23',
    authDomain: 'my-task-c7a23.firebaseapp.com',
    storageBucket: 'my-task-c7a23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHMD0PYfHi6VVrIi9P71CMp_m-RfBCIA8',
    appId: '1:201628199416:android:9ae798c7857bd8cd068e0d',
    messagingSenderId: '201628199416',
    projectId: 'my-task-c7a23',
    storageBucket: 'my-task-c7a23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF8auWHcWOg2UOKbm6o6FHqDPx8FcpFfg',
    appId: '1:201628199416:ios:35e7a94940ae52d2068e0d',
    messagingSenderId: '201628199416',
    projectId: 'my-task-c7a23',
    storageBucket: 'my-task-c7a23.appspot.com',
    iosClientId: '201628199416-1t4ivn7vvob0drsr6fm9pj41e2c96g9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF8auWHcWOg2UOKbm6o6FHqDPx8FcpFfg',
    appId: '1:201628199416:ios:35e7a94940ae52d2068e0d',
    messagingSenderId: '201628199416',
    projectId: 'my-task-c7a23',
    storageBucket: 'my-task-c7a23.appspot.com',
    iosClientId: '201628199416-1t4ivn7vvob0drsr6fm9pj41e2c96g9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoflutter',
  );
}
